version: "3.2"

services:
  dev:
    container_name: appchain-sopometa
    image: paritytech/ci-linux:974ba3ac-20201006
    working_dir: /var/www/appchain-sopometa
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/appchain-sopometa/.cargo
    volumes:
      - .:/var/www/appchain-sopometa
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/appchain-sopometa --dev --ws-external"
